name: Deploy via SSH

on:
  push:
    branches: ['main']

jobs:
  webpack:
    uses: ./.github/workflows/webpack.yml
  deploy:
    needs: webpack
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: setInNextStep

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Executing SSH Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd KalliopeServer
            git fetch
            git reset --hard FETCH_HEAD
            npm ci --omit=dev
            npx webpack
            screen -S KalliopeServer -X quit
            screen -dmS KalliopeServer bash -c "cd ~/KalliopeServer; node ."
