name: ESLint

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node Dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .
