name: Build Docs

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node Dependencies
        run: npm i jsdoc
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate documentation
        run: |
          npm run docs
          cd docs
          touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: docs
