name: Build Docs

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node Dependencies
        run: npm ci

      - name: Generate documentation
        run: |
          npm run docs
          cd docs
          touch .nojekyll

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Deploy JSDoc'
          branch: main