name: Build Docs

on:
  - push
  - workflow_dispatch

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node Dependencies
        run: npm i jsdoc

      - name: Generate documentation
        run: |
          npm run docs
          cd docs
          touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: docs
